# Generated by Django 4.2.1 on 2023-10-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos'),
        ),
    ]
