# Generated by Django 4.2.1 on 2023-12-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0002_alter_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dislike_count',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='video',
            name='like_count',
        ),
    ]
