# Generated by Django 4.2.1 on 2023-12-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0004_alter_channel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default_image_thumbnail.png', upload_to='thumbnails'),
        ),
    ]
