# Generated by Django 4.2.1 on 2023-12-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
