# Generated by Django 4.2.1 on 2023-12-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0006_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default_image_thumbnail.png', upload_to='thumbnails'),
        ),
    ]
