# Generated by Django 4.2.1 on 2023-12-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0007_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
